function dipCalc(){if(!_dipDx.length){document.getElementById('dip-rr').innerHTML='<div class="emp"><p>请先添加主要诊断编码</p></div>';return}if(!D||!D.dip){document.getElementById('dip-rr').innerHTML='<div class="emp"><p>数据加载中...</p></div>';return}var dx=_dipDx[0],px=_dipPx[0],pv=parseFloat(document.getElementById('dpv').value)||13000,il=parseFloat(document.getElementById('dip-lv').value),ag=parseFloat(document.getElementById('dip-age').value),ci=parseFloat(document.getElementById('dip-cci').value);var allPx=_dipPx.concat(_dipPx2);var matches=[];D.dip.forEach(function(d){if(d.dx===dx.c){var sc=0;if(allPx.length>0){for(var i=0;i<allPx.length;i++){if(d.px===allPx[i].c){sc=Math.max(sc,3);break}else if(d.rpx===allPx[i].c){sc=Math.max(sc,2)}}if(sc===0)sc=1}else{sc=d.px?0:1}if(sc>0)matches.push({d:d,score:sc})}});if(!matches.length){var fuzzy=[];D.dip.forEach(function(d){if(d.dx&&dx.c&&(d.dx.startsWith(dx.c)||dx.c.startsWith(d.dx))){var sc=0.5;for(var i=0;i<allPx.length;i++){if(d.px===allPx[i].c||d.rpx===allPx[i].c){sc=Math.max(sc,1.5);break}}if(sc>0)fuzzy.push({d:d,score:sc})}});if(fuzzy.length){fuzzy.sort(function(a,b){return b.score-a.score});matches=fuzzy.slice(0,20)}}if(!matches.length){document.getElementById('dip-rr').innerHTML='<div class="emp"><p>未找到匹配的 DIP 病种组</p><p style="font-size:.78em;color:var(--text-dim)">诊断: '+dx.c+' '+dx.n+(allPx.length?' | 手术: '+allPx.map(function(p){return p.c}).join(', '):'')+'</p><p style="font-size:.78em;color:var(--text-dim)">该诊断/手术组合暂不在国家 DIP 2.0 核心病种库中</p></div>';return}matches.sort(function(a,b){return b.score-a.score});
// === CCI auto-detection from MCC/CC lists ===
var mccS=_drg?_drg.mccS:new Set,ccS=_drg?_drg.ccS:new Set,excl=_drg?_drg.excl:{},mccT=_drg?_drg.mccT:{},ccT=_drg?_drg.ccT:{};
var cciDx=[],cciLevel='无合并症',cciAuto=1.0;
// Check primary diagnosis
if(mccS.has(dx.c)){var tbl=mccT[dx.c]||'',exclCodes=excl[tbl]||[];if(exclCodes.indexOf(dx.c)<0){cciDx.push({c:dx.c,l:'MCC(严重)'});cciLevel='MCC(严重合并症)';cciAuto=1.35}}
else if(ccS.has(dx.c)){var tbl2=ccT[dx.c]||'',exclCodes2=excl[tbl2]||[];if(exclCodes2.indexOf(dx.c)<0){cciDx.push({c:dx.c,l:'CC(一般)'});cciLevel='CC(一般合并症)';cciAuto=1.0}}
if(cciDx.length===0&&mccS.has(dx.c)){cciDx.push({c:dx.c,l:'MCC(已排除)'});cciLevel='MCC(排除-与主诊冲突)'}
// Use auto-detected or manual CCI
var effCI=ci!==1.0?ci:cciAuto;
var html='<div class="clr"><h3 style="color:var(--success);margin-bottom:2px">匹配 '+matches.length+' 个 DIP 病种组</h3>';
html+='<div style="font-size:.78em;color:var(--text-dim);margin-bottom:12px">主诊: '+dx.c+' '+dx.n+(px?' | 主手术: '+px.c+' '+px.n:'')+(allPx.length>1?' | 其他手术: '+_dipPx2.map(function(p){return p.c}).join(', '):'')+' | 点值 '+pv.toLocaleString()+' | 系数 '+il.toFixed(2)+'×'+ag.toFixed(1)+'×'+effCI.toFixed(2)+(cciDx.length?' <span style="color:'+(cciLevel.indexOf('MCC')>=0?'var(--danger)':'var(--warning)')+'">[CCI: '+cciLevel+']</span>':'')+'</div>';
html+='<div style="display:flex;flex-direction:column;gap:8px">';matches.slice(0,15).forEach(function(m,i){var d=m.d,isTop=i===0;var estScore=Math.round(2000+parseInt(d.c.replace('DIP',''))*8);var pay=Math.round(estScore*pv/13000*il*ag*effCI);html+='<div class="dip-result-card'+(isTop?' primary':'')+'">';html+='<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><b style="font-size:1.05em;color:'+(isTop?'var(--accent)':'var(--text)')+'">'+d.c+'</b>';if(isTop)html+='<span style="font-size:.7em;padding:1px 6px;border-radius:6px;background:var(--accent);color:#fff">推荐</span>';html+='<span style="font-size:.78em;color:var(--text-dim)">'+(d.px?d.px+' '+d.pxn:'保守治疗')+'</span></div>';html+='<div style="font-size:.75em;color:var(--text-dim);margin-top:4px">诊断: '+d.dx+' '+d.dxn+'</div>';if(d.rpx)html+='<div style="font-size:.72em;color:var(--text-dim)">相关手术: '+d.rpx+' '+d.rpxn+'</div>';html+='<div style="font-size:.75em;margin-top:6px;padding-top:6px;border-top:1px dotted var(--border);display:flex;gap:14px;flex-wrap:wrap;align-items:center"><span>估算分值 <b style="color:'+(isTop?'var(--accent)':'var(--text-dim)')+'">'+estScore+'</b></span>'+(isTop?'<span>点值 <b>'+pv.toLocaleString()+'</b></span><span>等级系数 <b>'+il.toFixed(1)+'</b></span><span>年龄 <b>'+ag.toFixed(1)+'</b></span><span>CCI <b style="color:'+(effCI>1.0?'var(--danger)':'var(--text-dim)')+'">'+effCI.toFixed(2)+'</b></span>':'')+'<span style="font-size:.9em">≈ 预估支付 <b style="color:'+(isTop?'var(--success)':'var(--text)')+'">'+pay.toLocaleString()+'</b> 元</span></div>'});html+='</div><div style="font-size:.68em;color:var(--text-dim);margin-top:10px;padding-top:8px;border-top:1px dotted var(--border)">* 分值按DIP编码序号估算(实际由各地测定)；点值=年度基金预算÷总分值(每年核定)；CCI基于CHS-DRG 2.0国标MCC/CC自动检测(4477+8008条编码)'+(cciDx.length?' | 本次检测: '+cciDx.map(function(x){return x.c+'['+x.l+']'}).join(', '):'')+'</div></div>';document.getElementById('dip-rr').innerHTML=html}
